### ISSUE TITLE
Extract Image with IMU Data

### ISSUE THREAD

**Issue by pmd2245** [ittybittyapps/ARRecorder#2]
Hi Vlas,

Thanks for your job about your article "Recording ARKit Sessions" and the code which comes with. 
I am currently looking for a way to extract the IMU data for each captured image. I did not find any way to do it using the example you have provided. 
Are the IMU data encoded with the video? Is there a solution to get them?

Thanks

**Comment by vlas-voloshin** [comment]
Hi, and sorry for taking so long to respond – I didn't get a notification about your issue.

I'm confident that the QuickTime video file that represents a session replay contains the gyro/accelerometer data as synchronised metadata tracks, so it _should_ be possible to extract it. However, the particular format this data is stored in those tracks is a private implementation detail, so it might not be trivial to extract it. You may essentially need to reverse-engineer a part of `ARReplaySensor` class from ARKit in order to do that, using something like Hopper Disassembler. I'd start at `initializeAssetReaderWithAsset:buffersOnly:` method where `AVAssetReader`, `AVAssetReaderTrackOutput` and `AVAssetReaderOutputMetadataAdaptor` objects from AVFoundation are used for these purposes, and then continue in `loadAllMetadata` method where the actual data is unpacked from adapters into specialised data classes like `ARAccelerometerData`, `ARGyroscopeData`, etc. However, it is possible that the actual format this data is stored in could be JSON, which could make the format more obvious, if you can just extract it from the tracks first.

I'm afraid there's not much I can help you with this beyond this advice though. Good luck!

**Comment by orj** [comment]
Hi folks, :wave: unfortunately we are not actively maintaining this project. 

Apple are free to change their private SPI at any time so supporting projects that use private SPI can be difficult. We've chosen to archive this project but that doesn't mean it couldn't be modified to work with newer OS releases given enough spelunking through API's private SPI.

Please feel free to fork and resurrect this code if you want to give that a try. 

Thanks 🙏
